languageCode = "en-us"
title = "Ratxabox"
baseurl = "http://x-gsm.fr/"
# Modifiez le thème pour qu'il soit utilisé par défaut à chaque génération de site.
theme = "hugo-theme-learn"

# Pour la fonctionnalité de recherche
[outputs]
home = [ "HTML", "RSS", "JSON"]

